%YAML:1.0
flipHorizontal: 0
flipVertical: 0
rotationDegrees: 0
blurKernelSize: 1
cannyThreshold1: 100
cannyThreshold2: 200
digitMinHeight: 20
digitMaxHeight: 90
digitYAlignment: 10
ocrMaxDist: 600000.
mysqlHost: "localhost"
mysqlUser: "root"
mysqlPassword: "root"
mysqlDatabase: "emeter"
trainingDataFilename: "training.yml"
